### ISSUE TITLE
lib/rest_kubernetes.rb argument number

### ISSUE THREAD

**Issue by xingxingxia** [openshift/verification-tests#118]
https://github.com/openshift/verification-tests/pull/88/ is a great PR. Found an issue related to it: `self.populate` adds 4th argument `type` in method def but leaves all callings still only 3 arguments without 4th argument `type`. This makes below failure, like in [the log](http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2019/03/15/07:09:31/PDB_take_effective_with_percentage_number_with_beta1/console.html):
```
wrong number of arguments (given 3, expected 4)
ArgumentError
/home/jenkins/workspace/Runner-v3/lib/rest_kubernetes.rb:8:in `populate'
/home/jenkins/workspace/Runner-v3/lib/rest_kubernetes.rb:79:in `create_pod_eviction'
/home/jenkins/workspace/Runner-v3/lib/rest.rb:101:in `delegate_rest_request'
/home/jenkins/workspace/Runner-v3/lib/rest.rb:27:in `exec'
/home/jenkins/workspace/Runner-v3/lib/api_accessor.rb:67:in `rest_request'
/home/jenkins/workspace/Runner-v3/lib/api_accessor_owner.rb:28:in `public_send'
/home/jenkins/workspace/Runner-v3/lib/api_accessor_owner.rb:28:in `block (2 levels) in '
/home/jenkins/workspace/Runner-v3/features/step_definitions/common.rb:26:in `/^I perform the :([a-z_]*?) rest request with:$/'
features/tierN/admin/pod.feature:480:in `When I perform the :create_pod_eviction rest request with:'
```
The api's are diverse. @akostadinov @pruan-rht any idea?

**Comment by pruan-rht** [comment]
@akostadinov @xingxingxia addressed by PR https://github.com/openshift/verification-tests/pull/121

**Comment by akostadinov** [comment]
I have provided a possible solution as a comment to #121
