### ISSUE TITLE
Met "Selenium::WebDriver::Error::UnknownError" when launch auto for jenkins test cases with 3.11 cluster

### ISSUE THREAD

**Issue by xiuwang** [openshift/verification-tests#133]
See Runner-v3/39302/consoleFull
Runner-v3/39052/consoleFull

The error “Failed to decode response from marionette (Selenium::WebDriver::Error::UnknownError)”

Or [07:03:33] INFO> Launching Firefox Marionette/Geckodriver
      invalid argument: can't kill an exited process (Selenium::WebDriver::Error::UnknownError)

This failure could be resolved with setting BUSHSLICER_CONFIG
global:
  browser: chrome

**Comment by xiuwang** [comment]
I also met this error with 4.0 code, https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39361/consoleFull

**Comment by akostadinov** [comment]
need to debug but it is something between build of Firefox and webdriver. For the time beingyou'd need to use chrome :/

**Comment by akostadinov** [comment]
Just a status update. I have done a number of testing. I could reproduce the issue in a container but could not in a VM. That is same OS/ff/driver version. I suspect some resource in container is lower or some file is missing or something.

Unfortunately debug firefox build did not show me where issue lied. Needs more thinkering what might be wrong. Any ideas welcome.

**Comment by xiuwang** [comment]
For now, we use "browser: chrome" parameter to override firefox when launch automation

**Comment by akostadinov** [comment]
I think we can close and wait 3.11 EOL. For 4.x, if we see such issues it is worth more investigation.
