### ISSUE TITLE
Error from server (NotFound): replicationcontrollers "ldapserver-1" not found

### ISSUE THREAD

**Issue by rhpmali** [openshift/verification-tests#1333]
****Issue**:** 
Getting error for every LDAP auto test cases.

**Description:**

As per 4.5 changes in the oc, The oc run command can now only be used to create Pods. So other resources are not created with it. Because of this replicationcontroller is not creating and auto is failing on check point.

**Actual Result:**

Failing with error 
~~~
Error from server (NotFound): replicationcontrollers "ldapserver-1" not found
~~~

**Expected Result:** 
It should not fail when in use "I have LDAP service in my project" in auto.

**Additional Information:**

$ oc version
Client Version: 4.5.0-rc.2
Server Version: 4.5.0-rc.7

**Comment by rhpmali** [comment]
@akostadinov @liangxia Can you please check. Thanks

**Comment by akostadinov** [comment]
@rhpmali , do you know what current equivalent option is for getting old behavior? Or you think we should adapt for the lack of replication controller?

**Comment by rhpmali** [comment]
@akostadinov The reason I suggested for step defination change becasue I tried to create the replicationcontroller manaully for version 4.5 with 
~~~ 
  Scenario: Failed sync group should prompt tolerate errors when tolarate errors flag is true
    Given I have a project
    Given I obtain test data file "groups/replicacontroller.yaml"
    Given I run the :create admin command with:
            | f | replicacontroller.yaml |
            | n |<%= project.name %>|
    Then the step should succeed
    Given I have LDAP service in my project
    And admin ensure "<%= cb.ldap_pod.name %>" pod is deleted after scenario
    And admin ensure "ldapserver" pod is deleted after scenario


$ cat features/tierN/testdata/groups/replicacontroller.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  name: ldapserver-1
spec:
  replicas: 1
  selector:
    app: ldapserver
  template:
    metadata:
      name: ldapserver
      labels:
        app: ldapserver
    spec:
      containers:
      - name: ldapserver
        image: openshift/openldap-2441-centos7:latest
        ports:
        - containerPort: 389
~~~

It works on 4.5 but it will create conflit with version < 4.5. As step "I have LDAP service in my project" is creating LDAP server and resources.
May be I am not sure, if possible can we write if else in step_defination like If osp < 4.5 execute code A and else execute B?

Here is the link for successful pass: 
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1761/console

**Comment by akostadinov** [comment]
I still don't understand what steps exactly you want to be performed when 4.5+ and what steps  are needed for earlier versions. Could you clarify?

**Comment by rhpmali** [comment]
So here for < 4.5
No need to do any steps in auto case, Just use "**Given I have LDAP service in my project**" and it will create pod and replicacontroller. And test run works fine.

In 4.5+, oc has some changes its will just create pod and no other resources like replicacontoller.  Here is the change log: https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#ocp-4-5-oc-run-pod 

So When I am using 4.5 with the line **Given I have LDAP service in my project** in my auto, Its just creating pod and **not** the replicacotroller. And Step_definition has step as below to check if replicontroller is created or not ? If not created it fails. 

~~~
169     step %Q/I wait until replicationController "ldapserver-1" is ready/    
~~

So to overcome this replicacontroller issue, I have created it with manually as mentioned in previous comment. And its all working fine. Basically for 4.5 I am creating replicacontroller manually to pass the test case.

Now the issue is :

1] If I use the manually created replicacontroller autocase in version < 4.5 , it will create conflict as OC is also crating replicacontroller and test will fail. 
2] If I dont create rc manaully all the test cases will pass in < 4.5 version but it will fail in 4.5 as OC is not creating rc.

**Comment by akostadinov** [comment]
I think we can just look for the pod then. The RC seems to only be a convenient way to check pod has started properly. But we can query pod by label I guess and check its status. WDYT?

**Comment by rhpmali** [comment]
Yeah, Thats seems good way.

**Comment by akostadinov** [comment]
@rhpmali , up to trying to fix it yourself?

**Comment by rhpmali** [comment]
Sure, I will try and will let you know.

**Comment by rhpmali** [comment]
@akostadinov Please review PR : https://github.com/openshift/verification-tests/pull/1353

**Comment by rhpmali** [comment]
PR merged, closing this one.
