### ISSUE TITLE
undefined method `elif' for #<BushSlicer::DefaultWorld:0x0000000006294540> Did you mean? elsif NoMethodError

### ISSUE THREAD

**Issue by jianzhangbjz** [openshift/verification-tests#1876]
For the upgrading test(from 4.4 to 4.5), we get the below errors when running [OCP-22618](https://github.com/openshift/verification-tests/blob/master/features/upgrade/marketplace/upgrade.feature#L8):
```console
undefined method `elif' for #<BushSlicer::DefaultWorld:0x0000000006294540> Did you mean? elsif
NoMethodError
/home/jenkins/ws/workspace/Runner-v3/features/step_definitions/operators.rb:74:in `/^the marketplace works well$/'
/opt/rh/rh-ruby27/root/usr/share/ruby/forwardable.rb:235:in `invoke_dynamic_steps'
/home/jenkins/ws/workspace/Runner-v3/features/step_definitions/meta_steps.rb:48:in `block (2 levels) in '
/home/jenkins/ws/workspace/Runner-v3/lib/base_helper.rb:153:in `wait_for'
/home/jenkins/ws/workspace/Runner-v3/features/step_definitions/meta_steps.rb:43:in `/^I wait(?: up to ([0-9]+|<%=.+?%>) seconds)? for the steps to pass:$/'
features/upgrade/marketplace/upgrade.feature:23:in `And I wait up to 360 seconds for the steps to pass:'
```
Full logs: http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2021/02/24/16:20:21/upgrade_Marketplace_-_prepare/console.html
The cluster is [140396](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Launch%20Environment%20Flexy/140396/), I checked the log and it works as expected. And, based on my understanding, the original cluster is 4.4, and it should run this part: https://github.com/openshift/verification-tests/blob/master/features/step_definitions/operators.rb#L62-L73 and then return. But, I'm not sure why failed on this step: https://github.com/openshift/verification-tests/blob/master/features/step_definitions/operators.rb#L74

**Comment by jianzhangbjz** [comment]
@akostadinov Any ideas? Or am I missing something?

**Comment by pruan-rht** [comment]
@jianzhangbjz it's just a typo...should be simple to fix...  I'll file a PR

**Comment by pruan-rht** [comment]
@jianzhangbjz https://github.com/openshift/verification-tests/pull/1877 should fix this issue.
