### ISSUE TITLE
mffiedler test issue

### ISSUE THREAD

**Issue by mffiedler** [openshift/verification-tests#2013]
@openshift/team-sdn-qe testing ping.   Please +1 if received.

**Comment by kedark3** [comment]
Yes this works. +1

**Comment by anuragthehatter** [comment]
Awwsome. Working like a charm. Thanks

**Comment by asood-rh** [comment]
Works for me +1

**Comment by huiran0826** [comment]
Works for me +1

**Comment by zhaozhanqi** [comment]
Thanks @mffiedler  works for me

**Comment by yingwang-0320** [comment]
works for me +1

**Comment by pruan-rht** [comment]
closing this since this is a just a test.
