### ISSUE TITLE
Cucumber "Background" keyword is not supported

### ISSUE THREAD

**Issue by valtair1891** [openshift/verification-tests#2204]
Cucumber keyword is not supported in verification-tests

features/node/kata/install.feature: (7:3): expected: #TagLine, #ScenarioLine, #Comment, #Empty, **got 'Background:**' (Cucumber::Core::Gherkin::ParseError)
/usr/share/gems/gems/cucumber-core-8.0.1/lib/cucumber/core/gherkin/parser.rb:29:in `block in document'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:64:in `yield'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:64:in `block in yield_parse_errors'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:53:in `each'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:53:in `yield_parse_errors'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:42:in `rescue in block (2 levels) in messages'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:27:in `block (2 levels) in messages'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:79:in `yield'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:79:in `block (2 levels) in sources'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:78:in `each'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:78:in `block in sources'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:25:in `each'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:25:in `each'
/usr/share/gems/gems/cucumber-gherkin-15.0.2/lib/gherkin/stream/parser_message_stream.rb:25:in `block in messages'
/usr/share/gems/gems/cucumber-core-8.0.1/lib/cucumber/core/gherkin/parser.rb:21:in `each'
/usr/share/gems/gems/cucumber-core-8.0.1/lib/cucumber/core/gherkin/parser.rb:21:in `each'
/usr/share/gems/gems/cucumber-core-8.0.1/lib/cucumber/core/gherkin/parser.rb:21:in `document'
/usr/share/gems/gems/cucumber-core-8.0.1/lib/cucumber/core.rb:33:in `block in parse'
/usr/share/gems/gems/cucumber-core-8.0.1/lib/cucumber/core.rb:32:in `each'
/usr/share/gems/gems/cucumber-core-8.0.1/lib/cucumber/core.rb:32:in `parse'
/usr/share/gems/gems/cucumber-core-8.0.1/lib/cucumber/core.rb:24:in `compile'
/usr/share/gems/gems/cucumber-5.3.0/lib/cucumber/runtime.rb:79:in `run!'
/usr/share/gems/gems/cucumber-5.3.0/lib/cucumber/cli/main.rb:29:in `execute!'
/usr/share/gems/gems/cucumber-5.3.0/bin/cucumber:9:in `<top (required)>'
/home/valiev/bin/cucumber:23:in `load'
/home/valiev/bin/cucumber:23:in `<top (required)>'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/usr/share/gems/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/share/gems/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
[12:10:32] INFO> === At Exit ===

**Comment by pruan-rht** [comment]
@valtair1891 missed this one... my example listed below works... so it's probably something on your side.  Pls post your scenario for review.

```Feature: test `Background` keyword
 Background:
 Given I have a project

 @admin
 Scenario: background test one
 Given I store the schedulable nodes in the clipboard
 And evaluation of `project.name` is stored in the :proj_name clipboard
 And the expression should be true> cb.proj_name == project.name
Scenario: background test two
 Given evaluation of `project.name` is stored in the :proj_name clipboard
 And the expression should be true> cb.proj_name == project.name```
