### ISSUE TITLE
result contain 'STDERR' information when host run command with 'oc debug'

### ISSUE THREAD

**Issue by zhaozhanqi** [openshift/verification-tests#492]
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/50163/console

see above logs:
I want to run command `'/sbin/ip\ route\ show\ default\ \|\ awk\ \'/default/\ \{print\ \$5\}\'` on host.  and get the result `ens5`, but the `Result` also included the following information:
```
      STDERR:
      Starting pod/ip-10-0-51-233us-east-2computeinternal-debug ...
      To use host binaries, run `chroot /host`
      
      Removing debug pod ...
```

@akostadinov

**Comment by zhaozhanqi** [comment]
the logs should be removed
so I describe the issue again:
when execute `@result = host.exec_admin("/sbin/ip route show default | awk '/default/ {print $5}'")` , it will invoke 'oc debug node/xxxx' '/sbin/ip\ route\ show\ default\ \|\ awk\ \'/default/\ \{print\ \$5\}\' , but the output also contain the error:
```
      STDERR:
      Starting pod/ip-10-0-51-233us-east-2computeinternal-debug ...
      To use host binaries, run `chroot /host`
      
      Removing debug pod ...
```
So the return result include above error, it's not unexpected. Can we have a way to remove above error from the result.

**Comment by akostadinov** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1771549

**Comment by akostadinov** [comment]
You will have to perhaps just call `ip route show default` and then parse in a ruby step.
```
evaluation of `...` is stored in the :ip clipboard
```
