### ISSUE TITLE
lib/rest_openshift.rb self.populate update

### ISSUE THREAD

**Issue by xingxingxia** [openshift/verification-tests#85]
In 4.0 env, due to https://jira.coreos.com/browse/MSTR-306, `Given I have a project` fails with:
```
error getting self from api: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```
Apply below diff, `Given I have a project` then passes.
```
       def self.populate(path, base_opts, opts)
-        populate_common("/oapi/<oapi_version>", path, base_opts, opts)
+        populate_common("/apis/user.openshift.io/<oapi_version>", path, base_opts, opts)
       end
```
Need update it considering 3.x compatibility
@akostadinov @pruan-rht could you help?
CC @zhouying7780 @wjiangjay @zihantang-rh

**Comment by wjiangjay** [comment]
why not create a PR for this? 
or just want to make sure how to deal with this kind of issue?

I think it's not work with whole 3.x, since afaik separated apigroup is added in later 3.x.

**Comment by pruan-rht** [comment]
https://github.com/openshift/verification-tests/pull/84

**Comment by pruan-rht** [comment]
FYI `/oapi` was removed about a month ago: https://github.com/openshift/origin/pull/21782 . Also, I've tested the new path it works up until 3.6, before which we have to use the `/oapi` path

**Comment by xingxingxia** [comment]
Thank all.
> why not create a PR for this?

I didn't think out solution to be compatible with all 3.x versions.

**Comment by akostadinov** [comment]
are you using token users to hit this issue btw? Better use user:pass pairs anyway.

**Comment by xingxingxia** [comment]
No, I was just using user:pass
